### ISSUE TITLE
There i no file for registration (/auth/register) also cannot login with your email and password

### ISSUE THREAD

**Issue by mghulamm** [ahmaat19/MERN-Stack-Boilerplate#1]
when i click on register it take me to 404 Not Found page.please help us to fix this also when i put Email: [ahmed@websom.dev]
Password: 123456 its give error.how i can fix this please help me to fix error.thanks in advance.

**Comment by ahmedibra28** [comment]
- Sorry, I forgot to disable /auth/register, so the route did not exist.
- The readme has been updated. The default credential is in the readme file after seeding data.

Seed the data before using info@ahmedibra.com by going to http://localhost:{your_backend_port_number}/api/auth/seed?secret=js

**Comment by ahmaat19** [comment]
> when i click on register it take me to 404 Not Found page.please help us to fix this also when i put Email: [[ahmed@websom.dev](mailto:ahmed@websom.dev)] Password: 123456 its give error.how i can fix this please help me to fix error.thanks in advance.
